#
# This pipeline needs the following tasks from Tekton Catalog
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: main
  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - init
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"

    - name: test
      taskRef:
        name: nose
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
